### ISSUE TITLE
export predict.gamlss

### ISSUE THREAD

**Issue by benrosche** [gamlss-dev/gamlss#1]
I am using the gamlss package as part of my own R package that performs a certain variance decomposition. I use the main function "gamlss" and the "predict.gamlss" on new data. I have trouble running the predict method inside my R package because you do not export(predict.gamlss) and @importMethodsFrom gamlss predict.gamlss throws an error. Could you add predict.gamlss to your list of exported functions/methods?

**Comment by zeileis** [comment]
Ben @benrosche I just noticed this issue recently when I joined the `gamlss-dev` org. Is this still relevant?

If so, can you say why you need to call `predict.gamlss()` directly rather than just using `predict()` on a `gamlss` object? The latter is the intended use and should also work within a package.

**Comment by zeileis** [comment]
My feeling is that this is outdated so I'm closing it now. Feel free to post a new issue along with a better explanation/justification if you think that this is still relevant.
